version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: barbearia_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: barbearia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d barbearia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: